// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareStore.Domain;

namespace SoftwareStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201228152033__initial")]
    partial class _initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("f6a6898d-9bd3-4b44-9cba-d3b13aeb3258"),
                            RoleId = new Guid("80725dc8-353e-4b5f-9277-31739833ce2a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SoftwareStore.Domain.Entities.App.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63dc8fa6-07ae-4391-8916-e057f71239ce"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2013, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "The Best Selling Disk Utility Software just got even more powerful. Fix It Utilities Professional comes packed with cutting edge. New Features designed to let you take control of your PC. Featuring the exclusive patent pending piece Analyzer Technology, 400% Faster Windows Registry Repair, a new Program Optimizer and Anti Virus Engine, as well as a dramatically redesigned and more intuitive User Interface design, Fix It Utilities is clearly the most flexible, powerful yet easy to use piece utility program available.",
                            OS = "Windows Vista, Windows 8, Windows 10, Windows 7",
                            Price = 19.90m,
                            Title = "Fix-It Utilities Professional"
                        },
                        new
                        {
                            Id = new Guid("88acf17c-ce69-4475-a6b0-aefe8d6a6c88"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2020, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "This USB will allow you to re-install Mac on a new SSD Hard Drive, or recover your existing version if you are having system or software failure. Simple and easy to use, no guess work. Use it without technical skills. It will work with some qualifiers: your hardware must be functional and your hardware must be as close as possible to the original Apple approved for the system. The ideal install / upgrade would happen on an original machine.",
                            OS = "macOS X High Sierra 10.13",
                            Price = 28.00m,
                            Title = "Bootable USB Stick"
                        },
                        new
                        {
                            Id = new Guid("48b8cb74-94db-4641-9895-1de2f2be8827"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2019, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "PCmover Express 11 is the ONLY software that automatically transfers files, settings, and user profiles from an old PC to a new one! It’s the easiest way to move to a new PC without leaving anything behind, even when there are different versions of Windows on the old and new PC. Nothing is changed on the old PC and nothing is overwritten on the new PC.",
                            OS = "Windows Vista, Windows 8, Windows 10, Windows XP, Windows 7",
                            Price = 19.90m,
                            Title = "Laplink PCmover Express"
                        },
                        new
                        {
                            Id = new Guid("b2f97cfb-3fc6-454a-86a5-5a04c6cc779a"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "The most up to date Windows Emergency Boot Disk on the market! Below are a few of the things that this disk will do for you",
                            OS = "Windows 98, 2000, XP, Vista, 7, 10",
                            Price = 12.99m,
                            Title = "Ralix Windows Emergency Boot Disk"
                        },
                        new
                        {
                            Id = new Guid("82dd7661-6b9b-4f24-8439-2ce7ce0c566a"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "AVG TuneUp is 15 years of computer optimization expertise that jogs your old PC back in shape, or keeps your new one running as fast as day 1.",
                            OS = "Windows 8, Windows 10, Mac OS X, Windows 7, Android",
                            Price = 24.99m,
                            Title = "AVG TuneUp"
                        },
                        new
                        {
                            Id = new Guid("ac6bcfad-63a0-444a-a9d5-a58248bfbe0b"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2020, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "The Best Cloning Software. It Simply Works | Make an exact copy of HDD, SSD or NVMe SSD, with Dynamic Resizing | Available in CD-ROM and Download",
                            OS = "Windows Vista, Windows 8, Windows 10, Windows 7",
                            Price = 21.99m,
                            Title = "NTI Echo 5"
                        },
                        new
                        {
                            Id = new Guid("0b53d140-b2f4-4474-a890-a37a74cbad2d"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "Still pining for that brand-new PC feeling? Get it back — and keep it — with the optimization and cleaning tools offered by Avast Cleanup Premium.",
                            OS = "Windows",
                            Price = 19.99m,
                            Title = "Avast Cleanup Premium"
                        },
                        new
                        {
                            Id = new Guid("a23a5ff0-561d-4a7d-a867-eb1eeacf6306"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "This software will reset your Windows login password. it is compatible with Windows 10, 8.1, 8, 7",
                            OS = "Window 10, 8, 7, Vista, XP",
                            Price = 20.99m,
                            Title = "Windows Password Reset USB"
                        },
                        new
                        {
                            Id = new Guid("4b96e514-78a7-48da-90d5-4d2c07012a8f"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2020, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "Quite possibly the most comprehensive Windows optimization suite ever! Gain new disk space, disable unwanted services and boost your PC performance to the max! Protect your privacy and customize Windows to your needs.Enjoy steady performance and a lean, secure system!",
                            OS = "Windows 10, 8.1, 8, 7",
                            Price = 22.99m,
                            Title = "WinOptimizer 18"
                        },
                        new
                        {
                            Id = new Guid("cff12241-dec0-4d7a-9af3-edcfcd0bc194"),
                            AppUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateAdded = new DateTime(2012, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Information = "CleanMy Mac & PC is one of the best and easiest to use cleaning solutions on the market for your OS. It consists of CleanMyMac for Macs & CleanMyPC for Windows based computers. CleanMyMac is the ultimate tool to keep your Mac clean and healthy.",
                            OS = "Windows Vista, Mac OS X, Windows XP, Windows 7",
                            Price = 15.99m,
                            Title = "CleanMy Mac & PC"
                        });
                });

            modelBuilder.Entity("SoftwareStore.Domain.Entities.Users.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80725dc8-353e-4b5f-9277-31739833ce2a"),
                            ConcurrencyStamp = "f60086fb-95cb-4c84-a8ff-017d564de50f",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("SoftwareStore.Domain.Entities.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a6898d-9bd3-4b44-9cba-d3b13aeb3258"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d7148818-4177-44ff-af1e-611ba88bc0b5",
                            DateAdded = new DateTime(2020, 12, 28, 15, 20, 32, 796, DateTimeKind.Utc).AddTicks(1680),
                            Email = "admin@admin.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@admin.ru",
                            NormalizedUserName = "admin@admin.ru",
                            PasswordHash = "AQAAAAEAACcQAAAAEBNIssRVmy9xnr/OshkAv1doRYk6po79FgaDzZBh8WAAQjkTw+uCvydgkVHyctXlqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.ru"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SoftwareStore.Domain.Entities.Users.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SoftwareStore.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SoftwareStore.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SoftwareStore.Domain.Entities.Users.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftwareStore.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SoftwareStore.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
